
spring:
  datasource:
    password: springstudent
    username: springstudent
    url: jdbc:mysql://localhost:3306/student_tracker
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
    show-sql: true
